version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/server"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/assets/feed-mark"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/scripts/shots"
    schedule:
      interval: "weekly"
