// Shared seed data for all 3 RSS prototypes.
// 7 feeds, ~24 articles. No real brand names.
// Per FEATURES.md: no `starred` flag (starring dropped, #35), no per-feed `tag`
// (redundant with folder), no priority. Articles are sorted newest-first by `ts`.

const FEEDS = [
  { id: 'fieldnotes', name: 'Field Notes',   author: 'M. Quinn',     url: 'fieldnotes.observer/feed',  hue: 22,  folder: 'Craft',   unread: 4 },
  { id: 'theloop',    name: 'The Loop',      author: 'Daily Brief',  url: 'theloop.cc/rss',            hue: 215, folder: 'Tech',    unread: 7 },
  { id: 'coldtake',   name: 'Cold Take',     author: 'A. Mendez',    url: 'coldtake.blog/feed.xml',    hue: 0,   folder: 'Reading', unread: 2 },
  { id: 'atlas',      name: 'Atlas',         author: 'Various',      url: 'atlasessays.org/feed',      hue: 152, folder: 'Reading', unread: 3 },
  { id: 'garden',     name: 'The Garden',    author: 'R. Okafor',    url: 'okafor.garden/index.xml',   hue: 88,  folder: 'Craft',   unread: 1 },
  { id: 'frequencies',name: 'Frequencies',   author: 'L. Hara',      url: 'frequencies.fm/rss',        hue: 285, folder: 'Reading', unread: 5 },
  { id: 'plot',       name: 'The Plot',      author: 'Fiction Wkly', url: 'theplot.press/feed',        hue: 38,  folder: 'Reading', unread: 0 },
];

const FEED_BY_ID = Object.fromEntries(FEEDS.map(f => [f.id, f]));

// Articles. ts is hours-ago for easy formatting. `link` is what the ↗ Open button opens.
const ARTICLES = [
  { id: 'a01', feed: 'fieldnotes', title: 'On the slow disappearance of the affordance',
    link: 'https://fieldnotes.observer/affordance',
    excerpt: 'Buttons used to look like buttons. Now they look like text. Somewhere in the middle a generation of users learned to hover before they trusted.',
    minutes: 6, ts: 2, unread: true },
  { id: 'a02', feed: 'theloop', title: 'The week in displacement: agents, browsers, and the slow death of the tab',
    link: 'https://theloop.cc/displacement',
    excerpt: 'Three product launches converged on the same idea this week — that the browser tab, which has carried the web for thirty years, might finally be the wrong unit.',
    minutes: 11, ts: 4, unread: true },
  { id: 'a03', feed: 'coldtake', title: 'Against the algorithm of taste',
    link: 'https://coldtake.blog/algorithm-of-taste',
    excerpt: 'When the feed knows you better than your friends, you stop telling your friends what you like. You just send them the link.',
    minutes: 8, ts: 7, unread: true },
  { id: 'a04', feed: 'atlas', title: 'A short history of the marginalia',
    link: 'https://atlasessays.org/marginalia',
    excerpt: 'Long before the highlight and the bookmark, readers wrote in the gutters of their books — arguments, jokes, grocery lists, recipes, the names of children not yet born.',
    minutes: 18, ts: 9, unread: true },
  { id: 'a05', feed: 'garden', title: 'Things I learned from running a 3-person company for a year',
    link: 'https://okafor.garden/three-person',
    excerpt: 'It is mostly bookkeeping and Slack. The work is the easy part. What surprises you is how much of running a company is just remembering things on behalf of other people.',
    minutes: 9, ts: 14, unread: true },
  { id: 'a06', feed: 'frequencies', title: 'The B-side as a literary form',
    link: 'https://frequencies.fm/b-side',
    excerpt: 'There is a particular shape to a song that knows nobody is listening too carefully. It can wander. It can fail. It can be, occasionally, the best thing on the record.',
    minutes: 7, ts: 18, unread: true },
  { id: 'a07', feed: 'theloop', title: 'Memo: what the new on-device models actually change',
    link: 'https://theloop.cc/on-device',
    excerpt: 'TL;DR: latency, privacy, and the unit economics of a feature you can ship without an API key. The interesting consequence is what falls out of the cloud.',
    minutes: 5, ts: 22, unread: true },
  { id: 'a08', feed: 'fieldnotes', title: 'Notes from a week of redrawing the same icon',
    link: 'https://fieldnotes.observer/redrawing',
    excerpt: 'I redrew the same 16-pixel folder eighteen times. Here is what was wrong with each one, and what I learned about the medium of the small.',
    minutes: 4, ts: 26, unread: true },
  { id: 'a09', feed: 'atlas', title: 'The cartographer who quit',
    link: 'https://atlasessays.org/cartographer',
    excerpt: 'For thirty years she mapped the same valley. Then satellites came, and the maps got better, and the maps got worse, and she walked out one Tuesday and never came back.',
    minutes: 22, ts: 30, unread: true },
  { id: 'a10', feed: 'coldtake', title: 'The new sincerity is just the old sincerity with better lighting',
    link: 'https://coldtake.blog/new-sincerity',
    excerpt: 'A defense of earnestness, and a warning about its newest costumes.',
    minutes: 6, ts: 34 },
  { id: 'a11', feed: 'theloop', title: 'Friday links: bicycle infrastructure, the death of the homepage, a really good keyboard',
    link: 'https://theloop.cc/friday-links',
    excerpt: 'Seven things worth your time this week, in no particular order, all light reading except the one about keyboards which is unfortunately quite long.',
    minutes: 3, ts: 38 },
  { id: 'a12', feed: 'frequencies', title: 'On listening to an album in order, on purpose',
    link: 'https://frequencies.fm/in-order',
    excerpt: 'Track 4 of a great record is doing something specific. It is not the single. It is not the closer. It is the joint. Without it the building leans.',
    minutes: 9, ts: 44 },
  { id: 'a13', feed: 'garden', title: 'I built a weather station and learned nothing about the weather',
    link: 'https://okafor.garden/weather-station',
    excerpt: 'Three months of data later, the conclusion is that it rains here. Sometimes more. The project, however, was about the wire.',
    minutes: 12, ts: 50 },
  { id: 'a14', feed: 'fieldnotes', title: 'The case for the small, slow website',
    link: 'https://fieldnotes.observer/small-slow',
    excerpt: 'Why the page that takes a moment to come together is sometimes the one you remember. Loading states as composition.',
    minutes: 7, ts: 60 },
  { id: 'a15', feed: 'plot', title: 'Issue 41 — The Carpenter and the Sea',
    link: 'https://theplot.press/issue-41',
    excerpt: 'A new short story by E. Vasiliev, in three parts, about a furniture maker who finds a door in the wall of his shop he is sure he did not build.',
    minutes: 28, ts: 68 },
  { id: 'a16', feed: 'theloop', title: 'A field guide to the new database wars',
    link: 'https://theloop.cc/database-wars',
    excerpt: 'Four contenders, three architectures, and a really opinionated chart at the bottom of the page that will make at least one engineer write me an email.',
    minutes: 14, ts: 76 },
  { id: 'a17', feed: 'atlas', title: 'How to fail a search-and-rescue exam',
    link: 'https://atlasessays.org/sar-exam',
    excerpt: 'On preparation, panic, and the very specific way that ropes betray you. A first-person essay from inside a training week.',
    minutes: 16, ts: 84 },
  { id: 'a18', feed: 'coldtake', title: 'The third place is a Discord and that is fine',
    link: 'https://coldtake.blog/third-place',
    excerpt: 'A grumpy but ultimately optimistic argument about where community actually happens in 2026, and what we owe to the volunteer moderators holding it together.',
    minutes: 7, ts: 92 },
  { id: 'a19', feed: 'frequencies', title: 'Reviewed: a debut record that is mostly silence',
    link: 'https://frequencies.fm/silence-review',
    excerpt: 'Seventeen minutes of music across forty-one minutes of runtime. The space is the point. The space is also, occasionally, very boring.',
    minutes: 6, ts: 100 },
  { id: 'a20', feed: 'fieldnotes', title: 'Three product reviews are a system',
    link: 'https://fieldnotes.observer/system',
    excerpt: 'You cannot ship a product. You can only ship the system that the product is the first instance of. Once you accept this the work changes.',
    minutes: 8, ts: 110 },
  { id: 'a21', feed: 'garden', title: 'On keeping a paper logbook in 2026',
    link: 'https://okafor.garden/logbook',
    excerpt: 'The argument for writing it down by hand is not nostalgia. It is that you remember things you wrote in a notebook. You do not remember anything you typed.',
    minutes: 5, ts: 124 },
  { id: 'a22', feed: 'theloop', title: 'The unbundling of the inbox',
    link: 'https://theloop.cc/unbundling',
    excerpt: 'Email is being broken into nine smaller products, each of which is better at one thing email used to do. A map.',
    minutes: 10, ts: 140 },
  { id: 'a23', feed: 'atlas', title: 'The town that voted to turn off the streetlights',
    link: 'https://atlasessays.org/streetlights',
    excerpt: 'A small place in the north of the country ran an experiment with darkness. The stars came back. So did some other things.',
    minutes: 19, ts: 168 },
  { id: 'a24', feed: 'plot', title: 'Issue 40 — Three Letters from the Lighthouse',
    link: 'https://theplot.press/issue-40',
    excerpt: 'Found correspondence, possibly fictional, between a keeper, his daughter, and the woman who delivered the mail by boat for eleven years.',
    minutes: 24, ts: 200 },
];

// Long-form body for the reader view. We re-use this for every article.
// Original prose; no copyrighted material.
const ARTICLE_BODY = [
  "There is a particular kind of attention that the small screen does not allow for, and I have been trying, badly and on and off, to recover it for years. It involves sitting still. It involves not knowing how long you have been sitting. It involves, crucially, the absence of a small red dot in the corner of any rectangle in the room.",
  "I do not want to make a moral argument about this. The dots are fine. The rectangles are fine. The argument I want to make is closer to the one a carpenter would make about a chisel: that the tool shapes the work, and the work shapes the maker, and so a tool that interrupts you eighty times an hour is going to produce a particular kind of person, regardless of that person's intentions.",
  "What I have noticed in the last year, mostly by accident, is that the act of subscribing to something — anything — is the closest the modern web has to a vow. You are telling a stranger: I trust you with twenty minutes of my Tuesday. Show up. Be worth it.",
  "And the strangers, in my experience, mostly do show up. Mostly are worth it. The web is full of people writing carefully for an audience of forty-three. The trick is finding them, and then, harder, the trick is reading them — actually reading them, not bookmarking them for a later that never comes.",
  "This is, I think, what RSS was for, and what it might yet be for again. Not a feed. A discipline.",
];

Object.assign(window, { FEEDS, FEED_BY_ID, ARTICLES, ARTICLE_BODY });
